version: '3.7'

services:
  app:
    build: .
    ports:
      - "8081:8081"
    networks:
      - s-network

  mysql:
    image: mysql:8.4
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: students
      MYSQL_USER: student
      MYSQL_PASSWORD: student123

    ports:
      - "3307:3306"

    volumes:
      - mysql-data:/var/lib/mysql
    
    networks:
      - s-network

volumes:
  mysql-data:

networks:
  s-network:
    driver: bridge