spring.application.name=AIDemo

spring.ai.anthropic.api-key=YOUR_API_KEY
spring.ai.ollama.chat.model=deepseek-r1:7b
spring.ai.google.genai.api-key=YOUR_API_KEY
spring.ai.google.genai.chat.model=gemini-3.6-flash