spring.application.name=log4j

logging.level.root=INFO

logging.level.com.log4j=DEBUG

logging.level.com.log4j.Service1=TRACE

logging.pattern.console=%d - %c - : %p -> %m :: %M %n

logging.file.name=logs/application.log

logging.pattern.file=%d - %c - : %p -> %m :: %M %n